# -*- coding: utf-8 -*-
"""DSC_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUSwoaxqK6_BLXV9s9AsCvfxu8qDzBMW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
import plotly.express as px
import time
sns.set(rc = {'figure.figsize':(15,8)})

# Load and examine data
df = pd.read_csv('fraudTrain.csv')
df.isna().sum()

df.drop_duplicates(inplace=True)
df['amt'].describe()

np.percentile(df['amt'], 99)

# Amount vs fraud
ax = sns.histplot(x='amt', data=df[df.amt<=1000], hue='is_fraud', stat='percent', multiple='dodge', common_norm=False, bins=25)
ax.set_ylabel('Percentage in Each Type')
ax.set_xlabel('Transaction Amount in USD')
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])
plt.savefig('amount_vs_fraud.png', dpi=300, bbox_inches='tight')
plt.show()

# Gender vs Fraud
ax = sns.histplot(x='gender', data=df, hue='is_fraud', stat='percent', multiple='dodge', common_norm=False)
ax.set_ylabel('Percentage')
ax.set_xlabel('Credit Card Holder Gender')
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])
plt.savefig('gender_vs_fraud.png', dpi=300, bbox_inches='tight')
plt.show()

# Calculate the percentage difference
a = df[df['is_fraud']==0]['category'].value_counts(normalize=True).to_frame().reset_index()
a.columns=['category','not fraud percentage']

b = df[df['is_fraud']==1]['category'].value_counts(normalize=True).to_frame().reset_index()
b.columns=['category','fraud percentage']
ab = a.merge(b, on='category')
ab['diff'] = ab['fraud percentage'] - ab['not fraud percentage']

ax = sns.barplot(y='category', x='diff', data=ab.sort_values('diff', ascending=False))
ax.set_xlabel('Percentage Difference')
ax.set_ylabel('Transaction Category')
plt.title('The Percentage Difference of Fraudulent over Non-Fraudulent Transations in Each Spending Category')
plt.savefig('category_diff.png', dpi=300, bbox_inches='tight')
plt.show()

# Age vs fraud
import datetime as dt
df['age'] = dt.date.today().year - pd.to_datetime(df['dob']).dt.year
ax = sns.kdeplot(x='age', data=df, hue='is_fraud', common_norm=False)
ax.set_xlabel('Credit Card Holder Age')
ax.set_ylabel('Density')
plt.xticks(np.arange(0, 110, 5))
plt.title('Age Distribution in Fraudulent vs Non-Fraudulent Transactions')
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])
plt.savefig('age_vs_fraud.png', dpi=300, bbox_inches='tight')
plt.show()

# Month vs fraud
df['month'] = pd.to_datetime(df['trans_date_trans_time']).dt.month
ax = sns.histplot(data=df, x="month", hue="is_fraud", common_norm=False, stat='percent', multiple='dodge')
ax.set_ylabel('Percentage')
ax.set_xlabel('Month')
plt.xticks(np.arange(1, 13, 1))
ax.set_xticklabels(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])
plt.savefig('month_vs_fraud.png', dpi=300, bbox_inches='tight')
plt.show()

# Extract additional temporal features
df['hour'] = pd.to_datetime(df['trans_date_trans_time']).dt.hour
df['day'] = pd.to_datetime(df['trans_date_trans_time']).dt.dayofweek
df['month'] = pd.to_datetime(df['trans_date_trans_time']).dt.month

# Subset the training data to include only the features that we need
train = df[['category', 'amt', 'zip', 'lat', 'long', 'city_pop', 'merch_lat', 'merch_long', 'age', 'hour', 'day', 'month', 'is_fraud']]
# Convert category to dummy variables
train = pd.get_dummies(train, drop_first=True)
y_train = train['is_fraud'].values
X_train = train.drop("is_fraud", axis='columns').values

# Process test dataset
test = pd.read_csv('fraudTest.csv')
test['age'] = dt.date.today().year - pd.to_datetime(test['dob']).dt.year
test['hour'] = pd.to_datetime(test['trans_date_trans_time']).dt.hour
test['day'] = pd.to_datetime(test['trans_date_trans_time']).dt.dayofweek
test['month'] = pd.to_datetime(test['trans_date_trans_time']).dt.month
test = test[['category', 'amt', 'zip', 'lat', 'long', 'city_pop', 'merch_lat', 'merch_long', 'age', 'hour', 'day', 'month', 'is_fraud']]
# Convert category to dummy variables
test = pd.get_dummies(test, drop_first=True)
y_test = test['is_fraud'].values
X_test = test.drop("is_fraud", axis='columns').values

# Apply SMOTE for handling class imbalance
from imblearn.over_sampling import SMOTE
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc, precision_recall_curve, average_precision_score

method = SMOTE()
X_resampled, y_resampled = method.fit_resample(X_train, y_train)

# Dictionary to store models, predictions and training times
models = {}
predictions = {}
training_times = {}

# 1. Logistic Regression
from sklearn.linear_model import LogisticRegression

start_time = time.time()
log_reg_model = LogisticRegression()
log_reg_model.fit(X_resampled, y_resampled)
log_reg_predicted = log_reg_model.predict(X_test)
log_reg_time = time.time() - start_time

print("Logistic Regression Results:")
print('Classification report:\n', classification_report(y_test, log_reg_predicted))
conf_mat_log_reg = confusion_matrix(y_true=y_test, y_pred=log_reg_predicted)
print('Confusion matrix:\n', conf_mat_log_reg)
print(f"Training and prediction time: {log_reg_time:.2f} seconds")
print('Share of Non-Fraud in Test Data:', 1-round(y_test.sum()/len(y_test), 4))
print("-" * 50)

# 2. Decision Tree
from sklearn.tree import DecisionTreeClassifier

start_time = time.time()
dt_model = DecisionTreeClassifier(max_depth=10, random_state=42)
dt_model.fit(X_resampled, y_resampled)
dt_predicted = dt_model.predict(X_test)
dt_time = time.time() - start_time

print("Decision Tree Results:")
print('Classification report:\n', classification_report(y_test, dt_predicted))
conf_mat_dt = confusion_matrix(y_true=y_test, y_pred=dt_predicted)
print('Confusion matrix:\n', conf_mat_dt)
print(f"Training and prediction time: {dt_time:.2f} seconds")
print("-" * 50)

# 3. XGBoost
import xgboost as xgb

start_time = time.time()
xgb_model = xgb.XGBClassifier(n_estimators=100, max_depth=5, random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(X_resampled, y_resampled)
xgb_predicted = xgb_model.predict(X_test)
xgb_time = time.time() - start_time

print("XGBoost Results:")
print('Classification report:\n', classification_report(y_test, xgb_predicted))
conf_mat_xgb = confusion_matrix(y_true=y_test, y_pred=xgb_predicted)
print('Confusion matrix:\n', conf_mat_xgb)
print(f"Training and prediction time: {xgb_time:.2f} seconds")
print("-" * 50)

# Store all model results for comparison
models = {
    'Logistic Regression': log_reg_model,
    'Decision Tree': dt_model,
    'XGBoost': xgb_model
}

predictions = {
    'Logistic Regression': log_reg_predicted,
    'Decision Tree': dt_predicted,
    'XGBoost': xgb_predicted
}

training_times = {
    'Logistic Regression': log_reg_time,
    'Decision Tree': dt_time,
    'XGBoost': xgb_time
}

# Create a summary dataframe with key metrics
summary = []
for name, pred in predictions.items():
    report = classification_report(y_test, pred, output_dict=True)
    summary.append({
        'Model': name,
        'Accuracy': report['accuracy'],
        'Precision': report['1']['precision'],
        'Recall': report['1']['recall'],
        'F1 Score': report['1']['f1-score'],
        'Time (s)': training_times.get(name, 'N/A')
    })

summary_df = pd.DataFrame(summary)
print("Model Comparison Summary:")
print(summary_df.sort_values('F1 Score', ascending=False))

# Visualizations for model comparison
# 1. ROC Curve Comparison
plt.figure(figsize=(16, 12))

plt.subplot(2, 2, 1)
for name, model in models.items():
    if hasattr(model, 'predict_proba'):
        y_score = model.predict_proba(X_test)[:, 1]
        fpr, tpr, _ = roc_curve(y_test, y_score)
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, lw=2, label=f'{name} (AUC = {roc_auc:.3f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend(loc="lower right")

# 2. Precision-Recall Curve
plt.subplot(2, 2, 2)
for name, model in models.items():
    if hasattr(model, 'predict_proba'):
        y_score = model.predict_proba(X_test)[:, 1]
        precision, recall, _ = precision_recall_curve(y_test, y_score)
        avg_precision = average_precision_score(y_test, y_score)
        plt.plot(recall, precision, lw=2, label=f'{name} (AP = {avg_precision:.3f})')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve Comparison')
plt.legend(loc="best")

# 3. F1 Score Comparison
plt.subplot(2, 2, 3)
sns.barplot(x='Model', y='F1 Score', data=summary_df)
plt.title('F1 Score Comparison')
plt.ylim([0, 1])

# 4. Training Time Comparison
plt.subplot(2, 2, 4)
sns.barplot(x='Model', y='Time (s)', data=summary_df)
plt.title('Training Time Comparison')

plt.tight_layout()
plt.savefig('model_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

# Individual model visualizations
# 1. Confusion Matrix for each model
plt.figure(figsize=(18, 6))

# Logistic Regression
plt.subplot(1, 3, 1)
sns.heatmap(confusion_matrix(y_test, log_reg_predicted), annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Fraud', 'Fraud'], yticklabels=['Not Fraud', 'Fraud'])
plt.title('Logistic Regression Confusion Matrix')

# Decision Tree
plt.subplot(1, 3, 2)
sns.heatmap(confusion_matrix(y_test, dt_predicted), annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Fraud', 'Fraud'], yticklabels=['Not Fraud', 'Fraud'])
plt.title('Decision Tree Confusion Matrix')

# XGBoost
plt.subplot(1, 3, 3)
sns.heatmap(confusion_matrix(y_test, xgb_predicted), annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Fraud', 'Fraud'], yticklabels=['Not Fraud', 'Fraud'])
plt.title('XGBoost Confusion Matrix')

plt.tight_layout()
plt.savefig('confusion_matrices.png', dpi=300, bbox_inches='tight')
plt.show()

# 2. Feature Importance (for Decision Tree and XGBoost)
plt.figure(figsize=(18, 12))

# Decision Tree Feature Importance
plt.subplot(2, 1, 1)
feature_names = train.drop('is_fraud', axis=1).columns
dt_importances = dt_model.feature_importances_
dt_indices = np.argsort(dt_importances)[::-1]
plt.barh(range(15), dt_importances[dt_indices][:15], align='center')
plt.yticks(range(15), [feature_names[i] for i in dt_indices[:15]])
plt.xlabel('Feature Importance')
plt.title('Decision Tree - Top 15 Important Features')

# XGBoost Feature Importance
plt.subplot(2, 1, 2)
xgb_importances = xgb_model.feature_importances_
xgb_indices = np.argsort(xgb_importances)[::-1]
plt.barh(range(15), xgb_importances[xgb_indices][:15], align='center')
plt.yticks(range(15), [feature_names[i] for i in xgb_indices[:15]])
plt.xlabel('Feature Importance')
plt.title('XGBoost - Top 15 Important Features')

plt.tight_layout()
plt.savefig('feature_importance.png', dpi=300, bbox_inches='tight')
plt.show()

# 3. Probability Distribution for each model
plt.figure(figsize=(18, 6))

for i, (name, model) in enumerate(models.items(), 1):
    if hasattr(model, 'predict_proba'):
        plt.subplot(1, 3, i)
        probs = model.predict_proba(X_test)[:, 1]

        # Separate probabilities for actual fraud and non-fraud cases
        fraud_probs = probs[y_test == 1]
        non_fraud_probs = probs[y_test == 0]

        # Plot distributions
        plt.hist(non_fraud_probs, bins=50, alpha=0.5, label='Not Fraud', color='blue')
        plt.hist(fraud_probs, bins=50, alpha=0.5, label='Fraud', color='red')
        plt.xlabel('Predicted Probability of Fraud')
        plt.ylabel('Count')
        plt.title(f'{name} - Probability Distribution')
        plt.legend()

plt.tight_layout()
plt.savefig('probability_distributions.png', dpi=300, bbox_inches='tight')
plt.show()

